### ISSUE TITLE
Morning Session peer-to-peer code review

### ISSUE THREAD

**Issue by Besufekad-HAZ** [Reggeditt/todo-list-App2#3]
### The Overall code and list look great but there are some issues to fix. 👍🥇.... 
- Kindly fix the remove Icon functionality from the To-Do list as it isn't removing items.
https://github.com/Reggeditt/todo-list-App2/blob/70ffb085b91f7148a1126ce5851deb04bd26d542/src/index.js#L14-L16
- Kindly work on sorting and ordering the list as it has minor issues when ordering and sorting items list...the remove icons and checkboxes are not sorted accordingly...
https://github.com/Reggeditt/todo-list-App2/blob/f14bbaf7a7addf75b2fe24b481aa6baf92c3a275/src/index.js#L23-L49

**Comment by Reggeditt** [comment]
thanks for the review!
